services:
  - type: web
    name: shifts-by-psp-1
    runtime: docker
    rootDir: backend
    plan: free
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8000
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: shiftextra_db
      - key: ENVIRONMENT
        value: production